include wombat.conf

font_size 13
font_family Inconsolata

adjust_line_height 115%
#window_padding_width 5
enable_audio_bell false
cursor #cccccc
cursor_text_color #ffffff
cursor_shape block
# overrides beam default
shell_integration no-cursor
