include dayfox.conf

font_family Inconsolata Nerd Font
font_size 13
#adjust_line_height 125%
#window_padding_width 5
enable_audio_bell false
cursor #9e00a1
cursor_text_color #ffffff
cursor_shape block
