alias ll='ls -l'
alias la='ls -A'
alias l='ls -CF'
alias g='git'
alias v='nvim'
alias sandbox='cd ~/.local/dev/projects/sandbox'
alias bkp='cd ~/.local/dev/work/bkprecision'
alias nvc='cd ~/.config/nvim'
