#!/usr/bin/bash
# A development environment setup script for Ubuntu 22.04
# Notes:
# - Assumes SSH keys are already set up with Gitlab.

# install dependencies
sudo apt install git tmux software-properties-common ca-certificates lsb-release
apt-transport-https wget ninja-build gettext cmake unzip curl kitty -y

cd ~/.config
echo 'Copying over dotfiles...'
git clone https://gitlab.com/raraga/dotfiles

cp ~/.config/dotfiles/.bashrc ~/
mkdir ~/.config/kitty
cp ~/.config/dotfiles/kitty/kitty.conf ~/.config/kitty
cp ~/.config/dotfiles/kitty/current.conf ~/.config/kitty
mkdir ~/.config/tmux
cp ~/.config/dotfiles/tmux/.tmux.conf ~/.config/tmux/tmux.conf
source ~/.bashrc
echo 'Dotfiles have been copied!'

# FZF
echo 'Setting up FZF...'
git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
~/.fzf/install
source ~/.bashrc
echo 'FZF installed'

# php 8.2
# add the repository
echo 'Installing PHP via PPA repository...'
sudo add-apt-repository ppa:ondrej/php
sudo apt install php8.2 php8.2-cli php8.2-common php8.2-fpm php8.2-mysql php8.2-zip php8.2-gd php8.2-mbstring php8.2-curl php8.2-xml php8.2-bcmath -y
echo 'PHP installed!'

# install latest composer
echo 'Installing Composer...'
sudo apt install composer
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('sha384', 'composer-setup.php') === 'e21205b207c3ff031906575712edab6f13eb0b361f2085f1f1237b7126d785e826a450292b6cfd1d64d92e6563bbde02') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"
mv composer.phar /usr/local/composer
echo 'Composer installed!'

# build nvim with lua
# creating new directory for building local binaries
echo 'Creating local binary directory...'
mkdir ~/.local/bin
cd ~/.local/bin

echo 'Building Neovim from source...'
git clone https://github.com/neovim/neovim
cd neovim && make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install
echo 'Neovim has been built!'

echo 'Installing Lua'
sudo apt install lua5.4

echo 'Copying over Neovim configuration..'
cp -r  ~/.config/dotfiles/nvim ~/.config/
echo 'Configuration copied!'

# setup node via NVM (version 16 has been the most stable when using Laravel)
echo 'Setting up Node via NVM...'
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
source ~/.bashrc
# opt into using Node version 16
nvm install 16
echo 'Node has been set up!'

# installing inconsolata nerd font
sudo cp -r ~/.config/dotfiles/fonts/inconsolata /usr/share/fonts/truetype/
