set -g default-command /usr/bin/bash
set -g default-shell /usr/bin/bash
set-option -g status-style "fg=#2b2b2b bg=#607d8b"
set -g pane-active-border-style 'fg=#607d8b'
set -g pane-border-style 'fg=#607d8b'
set-option -g status-left-length 100
set-option -g status-right-length 100
set-option -g status-left " #{session_name}  "
set-option -g status-right "#{pane_title} "
set-option -g window-status-activity-style none
set-option -ga terminal-overrides ",xterm-256color:Tc"
set-option -g default-terminal "screen-256color"

bind C-c new-session
bind C-f command-prompt -p find-session 'switch-client -t %%'
bind - split-window -v
bind _ split-window -h

# pane navigation
bind -r h select-pane -L  # move left
bind -r j select-pane -D  # move down
bind -r k select-pane -U  # move up
bind -r l select-pane -R  # move right
bind > swap-pane -D       # swap current pane with the next one
bind < swap-pane -U       # swap current pane with the previous one

# pane resizing
bind -r H resize-pane -L 20
bind -r J resize-pane -D 20
bind -r K resize-pane -U 20
bind -r L resize-pane -R 20

# window navigation
unbind n
unbind p
bind -r C-h previous-window # select previous window
bind -r C-l next-window     # select next window
bind Tab last-window        # move to last active window

# reload configuration
bind r source-file ~/.tmux.conf \; display '~/.tmux.conf sourced'

# global fixes for neovim
set-option -g focus-events on
set-option -sg escape-time 10
