set -g default-command /usr/bin/zsh
set -g default-shell /usr/bin/zsh

set-option -g status-style "fg=#93a1a1 bg=#eee8d5"
set -g pane-active-border-style 'fg=#eee8d5'
set -g pane-border-style 'fg=#eee8d5'
set -g message-style "fg=#fdf6e3, bg=#af87af"

set-option -g status-left-length 100
set-option -g status-right-length 100
set-option -g status-left " #{session_name}  "
set-option -g status-right "#{pane_title}"
set-option -g window-status-current-style 'fg=#d75f87 bold'
set-option -g window-status-current-format '#I:#W'
set-option -g window-status-activity-style none
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",*:RGB"

bind C-c new-session
bind C-f command-prompt -p find-session 'switch-client -t %%'
bind - split-window -v
bind _ split-window -h

# pane navigation
bind -r h select-pane -L  # move left
bind -r j select-pane -D  # move down
bind -r k select-pane -U  # move up
bind -r l select-pane -R  # move right
bind > swap-pane -D       # swap current pane with the next one
bind < swap-pane -U       # swap current pane with the previous one

# pane resizing
bind -r H resize-pane -L 20
bind -r J resize-pane -D 20
bind -r K resize-pane -U 20
bind -r L resize-pane -R 20

# window navigation
unbind n
unbind p
bind -r C-h previous-window # select previous window
bind -r C-l next-window     # select next window
bind Tab last-window        # move to last active window

# reload configuration
bind r source-file ~/.config/tmux/tmux.conf \; display 'config sourced!'

# global fixes for neovim
set-option -g focus-events on
set-option -sg escape-time 10
